refactor(refreshTimeButton): pf4 refreshTimeButton component
quipucords/quipucords-ui pull request #114
Opened 2022-07-06 19:53 UTC by andyyvo

## What's included

Closes #102

Refactoring `refreshTimeButton.js` to PF4 component/styling

### Notes

Styling issue. PF-react-core `Button` with `variant="link"` makes button blue. Also, old icon used is font-awesome refresh. However, PF icons does not have refresh so `RebootingIcon` was used. Additionally, there's an alignment styling issue.

## How to test

## Example

Before:
<img width="958" alt="Screen Shot 2022-07-06 at 3 40 13 PM" src="https://user-images.githubusercontent.com/58367784/177631428-b0abb078-77d0-449e-a18b-ef6f357c02a2.png">
<img width="958" alt="Screen Shot 2022-07-06 at 3 40 05 PM" src="https://user-images.githubusercontent.com/58367784/177631445-0ff6e0b2-5e4d-4ecc-8085-18060e69045f.png">

After:
<img width="958" alt="Screen Shot 2022-07-06 at 3 39 13 PM" src="https://user-images.githubusercontent.com/58367784/177631492-1a8e230f-9f8c-45bb-be08-2f489f241ee9.png">
<img width="958" alt="Screen Shot 2022-07-06 at 3 39 19 PM" src="https://user-images.githubusercontent.com/58367784/177631503-cf51ab54-6483-4421-9798-428b61ef9615.png">

## Updates issue/story

https://issues.redhat.com/browse/DISCOVERY-148

2022-07-06 21:12 UTC, cdcabrera requested changes
Looks good for a first round! Minor alteration to the locale string format requested.

@bclarhk should weigh in on the alignment of the SVG icon... seems to be another one we need to track (we think its related to the font-size adjustment)

And those unit test snapshots need to be updated, can walk you through if needed

2022-07-08 19:41 UTC, andyyvo commented
> Is this using the Tertiary button or Link button? It might just be the css alignment issue that's throwing me off...

@bclarhk link button

2022-07-09 09:01 UTC, cdcabrera approved these changes

2022-07-09 09:39 UTC, cdcabrera commented
As of 20220708 the icon alignment will be handled along with all the other icon alignments that have popped up during this set of refactors. See #118

2022-07-09 09:43 UTC, merged