refactor(buttons): convert buttons on Sources screen to PF4
quipucords/quipucords-ui pull request #136
Opened 2022-08-02 20:53 UTC by jenny-s51

## What's included

Towards #134, closes #135

**Before:**
<img width="1728" alt="Screen Shot 2022-08-02 at 4 46 02 PM" src="https://user-images.githubusercontent.com/32821331/182471045-e8eb434d-b2c2-4707-b82d-17f8250fd507.png">

**After:**
<img width="1728" alt="Screen Shot 2022-08-02 at 4 46 02 PM" src="https://user-images.githubusercontent.com/32821331/182471070-50e9da94-629f-457b-a6a6-e1b9928182d8.png">

2022-08-05 20:00 UTC, cdcabrera requested changes
Minor adjustments

2022-08-09 01:16 UTC, jenny-s51 reviewed
Thank you @cdcabrera - updated based on your suggestions to align with the recent pagination updates

2022-08-10 17:36 UTC, bclarhk approved these changes
Whee buttons!

2022-08-12 01:21 UTC, cdcabrera approved these changes

2022-08-12 01:32 UTC, merged