refactor(buttons): convert buttons in scans and sources list views
quipucords/quipucords-ui pull request #142
Opened 2022-08-15 18:10 UTC by jenny-s51

## What's included

...
Converts PF3 buttons to PF4 buttons in list view of Scans and Sources screens. 

**This includes the icons on the right of every list item, and the "Merge Reports" button on the Scans screen.**

## Example

...
### Before
<img width="1728" alt="Screen Shot 2022-08-15 at 2 07 09 PM" src="https://user-images.githubusercontent.com/32821331/184691303-9a63f9fb-d0fd-4552-8d9e-1cf183d21667.png">
<img width="1728" alt="Screen Shot 2022-08-15 at 2 07 24 PM" src="https://user-images.githubusercontent.com/32821331/184691307-96a2f87a-3adf-48fa-9365-ff40da322a2c.png">
<img width="1728" alt="Screen Shot 2022-08-15 at 2 07 50 PM" src="https://user-images.githubusercontent.com/32821331/184691310-b7b09f2b-9267-4087-83b8-bd6c6c2c1c9f.png">
<img width="1728" alt="Screen Shot 2022-08-15 at 11 43 26 AM" src="https://user-images.githubusercontent.com/32821331/184691313-b94844e0-dc33-4fa4-919c-eee60251ae5d.png">

### After
<img width="1728" alt="Screen Shot 2022-08-15 at 2 03 10 PM" src="https://user-images.githubusercontent.com/32821331/184691389-dd11a4b0-6343-49e8-adef-b4c32797842e.png">
<img width="1728" alt="Screen Shot 2022-08-15 at 2 03 55 PM" src="https://user-images.githubusercontent.com/32821331/184691392-e6c6860a-b352-46a0-b0b6-9f6bd19e5169.png">
<img width="1728" alt="Screen Shot 2022-08-15 at 2 04 43 PM" src="https://user-images.githubusercontent.com/32821331/184691396-f0a29778-b9b7-4b42-9115-06afcf865a9c.png">
<img width="1728" alt="Screen Shot 2022-08-15 at 2 06 07 PM" src="https://user-images.githubusercontent.com/32821331/184691398-ee74eb5f-eeb5-4cf8-bf4b-6aeeb49aa6ce.png">
<img width="1728" alt="Screen Shot 2022-08-15 at 2 06 38 PM" src="https://user-images.githubusercontent.com/32821331/184691401-e0d5831a-a24e-4367-bc57-45edf1bd6c59.png">

## Updates issue/story

2022-08-17 17:40 UTC, cdcabrera requested changes
Double check with Ben on the button but otherwise, lgtm!

2022-08-17 17:40 UTC, cdcabrera commented on src/components/scans/scans.js
> +            variant={ButtonVariant.secondary}
required:
investigate with UX @bclarhk to see if this should be a primary button

2022-08-18 17:04 UTC, bclarhk requested changes
Yeah, not sure why the merge reports is/was a secondary button. It's the only real action on the page. Let's make it the primary button.

2022-08-19 17:34 UTC, cdcabrera approved these changes

2022-08-19 19:46 UTC, jenny-s51 reviewed
Thank you for your reviews and feedback @cdcabrera @bclarhk ! 

I've switched the button to use the `primary` variant, and have uploaded a screenshot with the updated appearance of the "merge reports" button.

2022-08-19 19:46 UTC, merged