refactor(touchspin): convert touchspin to PF4
quipucords/quipucords-ui pull request #147
Opened 2022-08-26 16:16 UTC by jenny-s51

### Before
<img width="670" alt="Screen Shot 2022-08-26 at 12 13 56 PM" src="https://user-images.githubusercontent.com/32821331/186948333-23c37a9b-2388-4530-8497-4598603404fd.png">

### After
<img width="669" alt="Screen Shot 2022-08-26 at 12 12 56 PM" src="https://user-images.githubusercontent.com/32821331/186948360-98aa29ac-486b-4a5e-8a03-b56ebc32caec.png">

2022-08-26 18:07 UTC, cdcabrera requested changes
And lets restore the naming from numberInput to touchspin... that'll help us with history/tracking.

2022-08-26 18:07 UTC, cdcabrera commented on src/components/createScanDialog/createScanDialog.js
> +  renderConcurrentScans({ values }) {
required:
lets restore this, we think it's the cause of not submitting values... probably need to restore the "mockEvent" pieces too

2022-08-29 14:22 UTC, bclarhk approved these changes
silly number spinners. LGTM!

2022-08-29 17:39 UTC, cdcabrera requested changes

2022-08-29 17:39 UTC, cdcabrera commented on src/components/touchspin/touchspin.js
> +    let parsedValue = Number(event.target.value);
required:
`Number to Number.parseInt(yourstringnumberhere, 10)`

2022-08-31 17:21 UTC, cdcabrera requested changes

2022-08-31 17:21 UTC, cdcabrera commented on src/components/touchspin/touchspin.js
> -    parsedValue = Number.isNaN(parsedValue) ? minValue : parsedValue;
required:
going back through, this NaN check needs to be restored too, and possibly the rest of lines `84` through `90`

reason:
- Input fields regardless of whether they're declared "number" still return a string. the joys of HTML/JS interaction.
- this also covers the scenario when someone enters nothing but word, one of the reasons we call `parseInt`

2022-08-31 18:29 UTC, cdcabrera approved these changes
lgtm! much appreciated on the patience @jenny-s51

2022-08-31 18:35 UTC, merged