refactor(textArea): add PF4 textarea and use in form components
quipucords/quipucords-ui pull request #158
Opened 2022-09-08 18:35 UTC by jenny-s51

## What's included

...
Towards #104 : TextArea component

Adds new `TextArea` component to `forms`.

## Example

### Before 
<img width="1129" alt="Screen Shot 2022-09-08 at 11 55 29 AM" src="https://user-images.githubusercontent.com/32821331/189169928-af05dc00-d1f2-46ae-9316-e18bd5bea908.png">
<img width="685" alt="Screen Shot 2022-09-08 at 11 55 38 AM" src="https://user-images.githubusercontent.com/32821331/189169930-878ba0fb-7e5e-48b8-9628-b43f17002275.png">
<img width="602" alt="Screen Shot 2022-09-08 at 11 55 52 AM" src="https://user-images.githubusercontent.com/32821331/189169931-efcea95c-8e65-4aff-83fd-776b8e8caa91.png">

### After
<img width="680" alt="Screen Shot 2022-09-08 at 11 28 20 AM" src="https://user-images.githubusercontent.com/32821331/189170005-e8a0a364-4683-44d3-9b6c-3b6ee23e79a5.png">
<img width="604" alt="Screen Shot 2022-09-08 at 11 30 38 AM" src="https://user-images.githubusercontent.com/32821331/189170009-12ec6b3d-9b3e-4980-be32-dba16231ccd7.png">
<img width="604" alt="Screen Shot 2022-09-08 at 11 30 38 AM" src="https://user-images.githubusercontent.com/32821331/189170461-cad1112f-c96d-4d85-b685-c169ab3d0443.png">

@cdcabrera the credentials delete modal looks a bit different with the read-only PF4 `TextArea` styling. Might make more sense to use https://www.patternfly.org/v4/components/list/#list here instead? Let me know what you think!

2022-09-09 19:46 UTC, bclarhk requested changes
Agreed, wonky. Swap non-editable text out for the list view instead.

2022-09-12 17:24 UTC, cdcabrera approved these changes
lgtm

2022-09-12 17:27 UTC, cdcabrera requested changes

2022-09-12 17:27 UTC, cdcabrera commented on src/components/credentials/credentials.js
> +import { ListView } from 'patternfly-react';
required:
lets remove the credentials view work from this PR

2022-09-12 19:21 UTC, jenny-s51 reviewed
Thank you for your feedback @bclarhk @cdcabrera ! 

Per your comments, I have reverted the changes to the "Delete Credentials" modal.

2022-09-13 18:46 UTC, cdcabrera approved these changes

2022-09-13 21:33 UTC, cdcabrera commented
Went ahead and added a fix for the addSourceWizardStepTwo... apparently it was an older issue... the form would validate, a user could clear the fields and then still submit the form with the prior data

2022-09-13 23:47 UTC, merged