chore(refact): Disable the scan Merge Reports functionality.
quipucords/quipucords-ui pull request #243
Opened 2023-09-25 21:42 UTC by abellotti

The functionality has been broken for a while in the UI, and needs to be updated to leverage the async version of the API. For now we won't expose the Merge report Button and leave this as a CLI only functionality until the UI can be properly updated.

Before the disabling:

![Screenshot 2023-09-25 at 5 32 39 PM](https://github.com/quipucords/quipucords-ui/assets/5797328/ae027d61-0226-41f7-83f9-a738aeb727d9)

![Screenshot 2023-09-25 at 5 32 56 PM](https://github.com/quipucords/quipucords-ui/assets/5797328/b8b7f451-a68d-41fd-8f24-37846b6464c4)

After the disabling (Merge reports button is hidden):

![Screenshot 2023-09-25 at 5 31 27 PM](https://github.com/quipucords/quipucords-ui/assets/5797328/c45f21c0-95d6-47e9-aa34-b1eec09dda2d)

2023-09-25 22:08 UTC, bruno-fs reviewed
LGTM, but let's wait @cdcabrera 👀

2023-09-26 20:20 UTC, abellotti commented
@cdcabrera when you get a chance please.

2023-09-29 13:21 UTC, cdcabrera requested changes
This technically works! I think it's good as a temporary solution.

I would recommend a note in file referencing the Jira issue. If there isn't a Jira issue, I recommend you create one so there's some tracking on this, things seem to get lost.

Also recommend you

- include that Jira story reference in the commit message
- Refactor is an actual type you can use for the commit message...  message could be `refactor(scans): dis-[issue number] disable merge reports` (putting the entire DISCOVERY-[ISSUE NUM] in there is a little tedious)

2023-09-29 17:17 UTC, abellotti commented
There you go @cdcabrera 

Thank you for lending your 👀

2023-09-29 17:28 UTC, cdcabrera approved these changes

2023-09-29 17:30 UTC, merged