4 of 4, WIP build(deps): ds-661 pf5 package updates
quipucords/quipucords-ui pull request #349
Opened 2024-04-26 13:51 UTC by cdcabrera

## What's included

- build(deps): ds-661 pf5 package updates

## How to test

## Example

...

## Updates issue/story

[DISCOVERY-661](https://issues.redhat.com/browse/DISCOVERY-661)

2024-05-03 15:17 UTC, infinitewarp approved these changes

2024-05-03 18:57 UTC, nicolearagao approved these changes
LGTM

2024-05-06 11:27 UTC, mirekdlugosz requested changes
This introduces a problem with add source wizard. In step 1 I am supposed to select a source type. But clicking values does not change anything - default "Network Range" is still selected. I don't see any error in console either.

It looks like `handleOnEvent` does not modify `values.sourceType` (and possibly doesn't do other things it is supposed to be doing). I wasn't able to find this function actual code, so I can't verify that. From what I see, none of `addSourceWizardStepOne`, `formState`, `formGroup` or `Radio` were modified in this commit, so I have no idea why this would suddenly stop working.

2024-05-06 15:51 UTC, mirekdlugosz approved these changes
Yes, now the issue is fixed :) 

I think this is safe to merge, but we can't tag the new release with these changes until Camayoc PR is opened.

2024-05-06 17:30 UTC, merged