feat: ds-356 run the container without setting QUIPUCORDS_APP_PORT
quipucords/quipucords-ui pull request #445
Opened 2024-09-12 17:50 UTC by infinitewarp

## What's included
This enables a user to start a working container with just:

    podman run -p 9443:9443 quipucords-ui:latest

Previously the QUIPUCORDS_APP_PORT environment variable was required, and nginx would fail to start and present a very non-obvious error indicating its absence.

## How to test
```sh
podman build -t quipucords-ui:latest .
podman run -p 9443:9443 quipucords-ui:latest
# open https://localhost:9443 in a web browser to confirm it serves content
```

2024-09-12 18:06 UTC, nicolearagao approved these changes
lgtm

2024-09-12 18:42 UTC, cdcabrera requested changes
@infinitewarp heh, a limit on the number of characters for your commit message... `66` just needs to be `65` (obviously this can be done on squash or rebase merge)

2024-09-12 21:08 UTC, infinitewarp commented
> @infinitewarp heh, a limit on the number of characters for your commit message... `66` just needs to be `65` (obviously this can be done on squash or rebase merge)
> 
> It is acceptable to use the `build:` prefix instead of `feat:` ... the reasoning goes... since your work is affecting the ability to display actual UI features

@cdcabrera `build: ds-356 run the container without setting QUIPUCORDS_APP_PORT` would be even longer than the current message. What message would you use to satisfy this requirement while still conveying a meaningful description in the headline?

2024-09-12 21:33 UTC, cdcabrera commented
removing  the word "the" may meet the requirements
```
build: ds-356 run container without setting QUIPUCORDS_APP_PORT
```

2024-09-13 10:34 UTC, mirekdlugosz approved these changes
I would do:

    build: ds-356 set default value for QUIPUCORDS_APP_PORT

And in commit message body you can elaborate what problem this is solving.

2024-09-13 21:01 UTC, cdcabrera approved these changes

2024-09-13 21:01 UTC, merged