fix(showScansModal): ds-437 sort last scanned headers
quipucords/quipucords-ui pull request #502
Opened 2024-10-25 00:19 UTC by nicolearagao

Fix sorting mechanism in "Last Scanned" modal headers. 

### Notes
- fix to  [Mirek] “Last Scanned” modal. Clicking table header items inside modal does not actually change the order of items in table.
-This PR does not include pagination. If the number of scan jobs exceeds the visible screen area, you will need to scroll down to view all of them. However, sorting is applied across the entire list of scan jobs.

## How to test

### Coverage and basic unit test check
1. update the NPM packages with `$ npm install`
1. `$ npm test`
1. confirm tests come back clean

### Local run check
1. update the NPM packages with `$ npm install`
1. `$ npm run start`
1. confirm connections display as intended

## Example

## Updates issue/story

[DISCOVERY-437](https://issues.redhat.com/browse/DISCOVERY-437)

2024-10-25 10:33 UTC, mirekdlugosz approved these changes
Works as intended :+1:

2024-10-25 17:10 UTC, cdcabrera requested changes

2024-10-25 17:10 UTC, cdcabrera commented on src/views/scans/showScansModal.tsx
> +      return direction === 'asc' ? (valA > valB ? 1 : -1) : valA < valB ? 1 : -1;
required: as noted previously, nested ternaries can lead to confusion this should be updated... i'm having trouble reading this...

2024-10-25 17:13 UTC, cdcabrera commented on src/views/scans/showScansModal.tsx
> +  const sortJobs = (jobs: typeof scanJobs, index: number, direction: 'asc' | 'desc') => {
recommended:
you should consider breaking these helpers out into independent helper functions for testing

2024-10-25 17:19 UTC, cdcabrera commented on src/views/scans/showScansModal.tsx
> +      if (valA === valB) return 0; // Handle equal values
required: avoid not using brackets. add brackets back. combined with the below ternary this edges you closer to unreadable code

2024-10-28 19:53 UTC, nicolearagao commented on src/views/scans/showScansModal.tsx
> +      setSortedScanJobs(sortByLatestTime(scanJobs));
@cdcabrera After applying all the changes requested, the tests related to this modal were never finishing. I was running  into "Maximum component depth exceeded". This seemed to be causing infinite loops, due to re-rendering of parent component:
```
useEffect(() => {
  const initialSortedJobs = sortByLatestTime(scanJobs);
  setSortedScanJobs(initialSortedJobs);
}, [scanJobs]);
```
The solution I have now solves the problem, let me know if it was the best path forward.

2024-10-29 11:57 UTC, cdcabrera requested changes
1 minor update on the `useState` for `sortedScanJobs`, everything else is optional. you could also review the use of `return` in your helper arrow functions

2024-10-30 14:29 UTC, cdcabrera approved these changes
lgtm

2024-10-30 18:07 UTC, merged