Test DISCOVERY-437 (bonus: smoke test viewScanList!)
quipucords/quipucords-ui pull request #518
Opened 2024-11-14 20:00 UTC by bruno-fs

## What's included
Add a sanity check testing viewScanList and the behavior of the kebab
button;
    
Properly test DISCOVERY-437; given how tighly coupled everything is,
adding a view test was the only way to test it.

### Notes
changing jest config and adding babel as transformer was required to be able to test those views - setting up those configs was way more challenging than actually writing those tests 😅 

## How to test
npm test

### Coverage and basic unit test check
1. update the NPM packages with `$ npm install`
1. `$ npm test`
-->

## Example

...

## Updates issue/story

[DISCOVERY-437](https://issues.redhat.com/browse/DISCOVERY-437)

2024-11-14 20:13 UTC, cdcabrera commented
@bruno-fs the primary views were disabled from testing for multiple internal reasons discussed with @nicolearagao around how to architect UI code.

Any future "view" code actively needs to be broken apart into subsequent components, helpers, etc... before attempting to shoe-horn a testing solution into place. Some of the "many" future breakouts that need to happen include
- Toast notification alerts
- Table/inventory
- Moving API calls into the actual modals

...performing these types of updates will subsequently make testing the views easier. I recommend closing this PR down in the short term

2024-11-14 20:14 UTC, cdcabrera requested changes
This work should not be merged until an overarching understanding of future UI architecture is discussed or understood

2024-11-14 20:21 UTC, bruno-fs commented
That's an interesting point, @cdcabrera. While I agree the views (or at least this one) desperately needs a refactor that makes it more decoupled - and at the very minimum easier to test, I don't think testing them (at least smoke testing) should be postponed.

Waiting to test later is a liability and should be a team decision, not up to just you and @nicolearagao.

2024-11-22 15:26 UTC, bruno-fs commented
@mirekdlugosz it seems it won't be possible to test download functionality from scans page on this codebase.

I wrote this one because of your previous comment about having download functionality already covered on camayoc, but on the scan jobs modal... Do you have a suggestion on how to test this while the refactor doesn't happen?

2024-11-25 17:01 UTC, bruno-fs commented on src/views/scans/__tests__/viewScansList.test.tsx
> +    });
@cdcabrera just to be sure we are on the same page, if I remove all the proposed tests but this one (this was the true goal of testing here), would you still be against this PR?

2024-12-18 16:50 UTC, mirekdlugosz commented
@bruno-fs just FYI, covering both paths to download report (kebab menu and modal) is introduced in https://github.com/quipucords/camayoc/pull/557

2025-01-07 19:01 UTC, closed without merging